

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AddProductButton } from '@/app/Components/AddProductButton'
import Link from 'next/link'
import { AddCartButton } from './Components/AddCartButton'
import Navbar from './Components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lazapee',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
    </html>
  )
}
